export const portfolioContent = {
  en: {
    pageTitle: "Yijun Yuan | Software Developer",
    nav: {
      backToTop: "Back to top",
      projects: "Projects",
      skills: "Skills",
      experience: "Experience",
      contact: "Contact",
      resume: "Resume",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      language: "Language",
    },
    hero: {
      terminalWords: [
        "software_developer",
        "product_designer",
        "qa_minded_builder",
        "fullstack_learner",
        "ship_useful_tools",
      ],
      kicker: "Software developer / CS student",
      greeting: "Hi, I'm",
      name: "Yijun Yuan",
      intro:
        "I'm a software developer and computer science student who enjoys turning ideas into real products. From full-stack web applications to AI-powered learning tools, I love building software that solves problems and creates meaningful experiences.",
      subnote:
        "I'm always exploring new technologies and looking for opportunities to learn, grow, and ship impactful products.",
      viewProjects: "View projects",
      initialize: "Initialize protocol",
      contact: "Contact node",
      explore: "Explore",
      console: {
        online: "interactive_protocol_online",
        title: "Interactive console",
        back: "Back to profile",
        placeholder: "try help, whoami, skills, projects, status...",
        execute: "EXEC",
        initial: [
          "YY_PORTFOLIO OS v1.0 initialized.",
          "LOADING PROJECT WORKSPACE...",
          "STATUS: AVAILABLE_FOR_HIRE",
          'Type "help" for available commands.',
          "",
        ],
        initialized: ["USER DISPATCHED: INITIALIZE_CONSOLE", "ACTIVE SYSTEM LINK ATTACHED.", ""],
        aliases: {},
        responses: {
          help: [
            "Available commands:",
            "  whoami    - Short profile",
            "  skills    - Current technical stack",
            "  projects  - Featured personal projects",
            "  status    - Availability and location",
            "  clear     - Clear terminal",
            "  exit      - Close interactive console",
          ],
          whoami: [
            "YIJUN YUAN // SOFTWARE DEVELOPER + CS STUDENT",
            "Builds practical tools, tests carefully, and learns by shipping real products.",
          ],
          skills: [
            "CORE STACK:",
            "  Frontend: React, JavaScript, HTML, CSS, Vite",
            "  Data:     Python, SQL, C",
            "  QA:       Manual testing, test cases, defect verification, automation",
          ],
          projects: [
            "FEATURED PROJECTS:",
            "  Apply Track  - Job application workflow system",
            "  French Desk  - AI-assisted French learning workspace",
          ],
          status: [
            "AVAILABILITY: AVAILABLE_FOR_HIRE",
            "LOCATION: Scarborough, Ontario",
            "FOCUS: Software development, QA, product-minded engineering",
          ],
        },
        closing: "CLOSING_CONSOLE...",
        unknownStart: "Command not recognized:",
        unknownEnd: 'Type "help" to view available commands.',
      },
    },
    projects: {
      kicker: "Core deployments",
      title: "Personal projects",
      status: "ACTIVE_CORES",
      filter: "All systems",
      searchPlaceholder: "Search projects, stack, workflow...",
      previewAction: "Open live preview",
      previewAlt: "product preview",
      liveSnapshot: "Live app snapshot",
      role: "Role",
      highlights: "highlights",
      openProject: "Open project",
      empty: "No projects match that search.",
      items: [
        {
          id: "apply-track",
          title: "Apply Track",
          category: "workflow",
          role: "Designer & Developer",
          href: "https://apply-track-six.vercel.app/",
          previewImage: "/project-previews/applytrack-dashboard.png",
          previewUrl: "https://apply-track-six.vercel.app/#/demo",
          previewLabel: "ApplyTrack live demo preview",
          copy: "A focused job application workspace built from a problem I was feeling directly.",
          problem:
            "It helps me keep companies, roles, statuses, imported spreadsheet rows, and next steps in one calmer place while job searching.",
          highlights: ["React", "Vite", "Spreadsheet import", "Personal workflow"],
        },
        {
          id: "french-desk",
          title: "French Desk",
          category: "learning",
          role: "Designer & Developer",
          href: "https://french-learning-theta.vercel.app/",
          previewImage: "/project-previews/frenchdesk-today.png",
          previewUrl: "https://french-learning-theta.vercel.app/#/demo",
          previewLabel: "French Desk live demo preview",
          copy: "A personal French learning hub for notes that were getting too hard to review.",
          problem:
            "It gives me a calmer place to collect vocabulary, phrases, grammar, pronunciation notes, quizzes, and short daily study sessions.",
          highlights: ["React", "Supabase", "Tailwind", "AI vocabulary autofill"],
        },
      ],
    },
    skills: {
      kicker: "Tech stack",
      title: "Technical proficiencies",
      intro:
        "A practical mix of frontend building, data workflows, and QA judgment. Click a card to inspect the current focus area.",
      activeFocus: "ACTIVE_FOCUS",
      verification: "VERIFICATION_STATUS",
      verificationValue: "learning_by_building",
      groups: [
        {
          id: "frontend",
          title: "Frontend Product Building",
          copy: "React interfaces, responsive layouts, product workflows, and UI polish that makes tools feel clear.",
          tags: ["React", "JavaScript", "HTML", "CSS", "Vite"],
        },
        {
          id: "data",
          title: "Data And Systems Thinking",
          copy: "Comfortable working around dashboards, collection workflows, validation rules, and data-heavy screens.",
          tags: ["Python", "SQL", "C", "Data workflows"],
        },
        {
          id: "qa",
          title: "QA Mindset",
          copy: "I look for edge cases, unclear states, broken assumptions, and details that create real user friction.",
          tags: ["Manual testing", "Test cases", "Defect reports", "Automation"],
        },
      ],
    },
    experience: {
      kicker: "Career log",
      title: "Professional journey",
      summaryTitle: "System metrics",
      summary:
        "Co-op roles where I contributed to production systems, QA workflows, and public-sector data tools.",
      roleCount: "Co-op roles",
      projectCount: "Product side projects",
      items: [
        {
          title: ".NET Developer Co-op",
          company: "Ontario Ministry of Education",
          period: "Sep 2024 - Dec 2024",
          logo: "ontario",
          copy: "During my developer co-op, I contributed to the development and maintenance of internal applications used by educators and ministry staff. I collaborated with developers and business stakeholders to implement new features, resolve issues, and improve application usability using .NET technologies and modern development practices.",
          tags: [".NET", "Web apps", "Stakeholder collaboration"],
        },
        {
          title: "IT QA Assistant Co-op",
          company: "Ontario Ministry of Education",
          period: "Jan 2024 - Aug 2024",
          logo: "ontario",
          copy: "As an IT QA Assistant, I was responsible for ensuring the quality and reliability of educational applications used across Ontario. I designed and executed test cases, reported and verified defects, and developed automation scripts to improve testing efficiency while working closely with developers and business teams.",
          tags: ["QA", "Automation", "HP ALM"],
        },
        {
          title: "Quality Assurance Tester Co-op",
          company: "Fresh City Farms",
          period: "Jan 2023 - Apr 2023",
          logo: "fresh",
          copy: "At Fresh City Farms, I supported the quality assurance process for the company's e-commerce platform and internal systems. I performed functional and regression testing, documented defects with detailed reproduction steps, and collaborated with developers to ensure a smooth and reliable user experience.",
          tags: ["Regression testing", "Jira", "E-commerce"],
        },
      ],
    },
    contact: {
      titleBefore: "Let's build something",
      titleAccent: "useful",
      intro:
        "Open to all kinds of opportunities where I can build useful products, contribute carefully, and keep growing while making impact.",
      messageTitle: "TRANSMIT_MESSAGE",
      message:
        "The fastest route is email. Send the context, the problem, and what kind of help you need.",
      copyEmail: "COPY_EMAIL_ADDRESS",
      copiedEmail: "EMAIL_COPIED",
      networkTitle: "NETWORK_NODES",
      professionalProfile: "Professional profile",
      resume: "Resume",
      resumeDetail: "Download PDF",
    },
    footer: {
      builtWith: "2026 // BUILT_WITH_REACT",
      status: "NODES_SECURE",
    },
  },
  zh: {
    pageTitle: "Yijun Yuan | 软件开发者",
    nav: {
      backToTop: "返回顶部",
      projects: "项目",
      skills: "技能",
      experience: "经历",
      contact: "联系",
      resume: "简历",
      openMenu: "打开菜单",
      closeMenu: "关闭菜单",
      language: "语言",
    },
    hero: {
      terminalWords: ["软件开发者", "产品设计者", "注重质量的构建者", "全栈学习者", "打造实用工具"],
      kicker: "软件开发者 / 计算机科学学生",
      greeting: "你好，我是",
      name: "Yijun Yuan",
      intro:
        "我是一名软件开发者和计算机科学专业学生，喜欢把想法变成真正可用的产品。从全栈 Web 应用到 AI 驱动的学习工具，我享受用软件解决问题，并创造有意义的使用体验。",
      subnote: "我一直在探索新技术，也在寻找能够学习、成长并交付有影响力产品的机会。",
      viewProjects: "查看项目",
      initialize: "启动交互终端",
      contact: "联系我",
      explore: "继续探索",
      console: {
        online: "交互终端已连接",
        title: "交互终端",
        back: "返回个人介绍",
        placeholder: "输入 help、whoami、skills、projects 或 status...",
        execute: "执行",
        initial: [
          "YY_PORTFOLIO OS v1.0 已启动。",
          "正在加载项目工作区...",
          "状态：正在寻找机会",
          '输入 "help" 查看可用命令。',
          "",
        ],
        initialized: ["用户指令：启动交互终端", "系统连接已建立。", ""],
        aliases: {
          帮助: "help",
          我是谁: "whoami",
          技能: "skills",
          项目: "projects",
          状态: "status",
          清屏: "clear",
          退出: "exit",
        },
        responses: {
          help: [
            "可用命令：",
            "  whoami    - 个人简介",
            "  skills    - 当前技术栈",
            "  projects  - 代表性个人项目",
            "  status    - 求职状态与所在地",
            "  clear     - 清空终端",
            "  exit      - 关闭交互终端",
          ],
          whoami: [
            "YIJUN YUAN // 软件开发者 + 计算机科学学生",
            "专注于构建实用工具、认真测试，并通过交付真实产品持续学习。",
          ],
          skills: [
            "核心技术栈：",
            "  前端：React、JavaScript、HTML、CSS、Vite",
            "  数据：Python、SQL、C",
            "  测试：手动测试、测试用例、缺陷验证、自动化",
          ],
          projects: [
            "代表项目：",
            "  Apply Track  - 求职申请流程管理系统",
            "  French Desk  - AI 辅助法语学习工作台",
          ],
          status: [
            "求职状态：正在寻找机会",
            "所在地：加拿大安大略省士嘉堡",
            "方向：软件开发、质量保证、产品导向工程",
          ],
        },
        closing: "正在关闭终端...",
        unknownStart: "无法识别命令：",
        unknownEnd: '输入 "help" 查看可用命令。',
      },
    },
    projects: {
      kicker: "核心项目",
      title: "个人项目",
      status: "运行中的项目",
      filter: "全部项目",
      searchPlaceholder: "搜索项目、技术或工作流...",
      previewAction: "打开在线预览",
      previewAlt: "产品预览",
      liveSnapshot: "在线应用预览",
      role: "职责",
      highlights: "项目亮点",
      openProject: "打开项目",
      empty: "没有符合搜索条件的项目。",
      items: [
        {
          id: "apply-track",
          title: "Apply Track",
          category: "工作流工具",
          role: "设计与开发",
          href: "https://apply-track-six.vercel.app/",
          previewImage: "/project-previews/applytrack-dashboard.png",
          previewUrl: "https://apply-track-six.vercel.app/#/demo",
          previewLabel: "ApplyTrack 在线演示预览",
          copy: "一套专注于求职流程的申请管理工具，源于我亲身遇到的问题。",
          problem: "它把公司、职位、申请状态、导入的表格数据和后续行动集中在一个更清晰的工作区中。",
          highlights: ["React", "Vite", "表格导入", "个人求职工作流"],
        },
        {
          id: "french-desk",
          title: "French Desk",
          category: "学习工具",
          role: "设计与开发",
          href: "https://french-learning-theta.vercel.app/",
          previewImage: "/project-previews/frenchdesk-today.png",
          previewUrl: "https://french-learning-theta.vercel.app/#/demo",
          previewLabel: "French Desk 在线演示预览",
          copy: "一个为了解决法语笔记越来越难复习而打造的个人学习中心。",
          problem: "它让我可以更有条理地整理词汇、短语、语法、发音笔记、测验和每日短时学习任务。",
          highlights: ["React", "Supabase", "Tailwind", "AI 词汇自动补全"],
        },
      ],
    },
    skills: {
      kicker: "技术栈",
      title: "技术能力",
      intro: "结合前端开发、数据工作流和质量保证判断力。选择卡片可以查看当前关注的能力方向。",
      activeFocus: "当前方向",
      verification: "实践状态",
      verificationValue: "在真实项目中持续学习",
      groups: [
        {
          id: "frontend",
          title: "前端产品开发",
          copy: "构建 React 界面、响应式布局和完整产品工作流，并通过细致打磨让工具更清晰易用。",
          tags: ["React", "JavaScript", "HTML", "CSS", "Vite"],
        },
        {
          id: "data",
          title: "数据与系统思维",
          copy: "能够处理仪表盘、数据收集流程、验证规则和信息密集型界面。",
          tags: ["Python", "SQL", "C", "数据工作流"],
        },
        {
          id: "qa",
          title: "质量保证思维",
          copy: "关注边界情况、模糊状态、错误假设，以及会给真实用户带来阻碍的细节。",
          tags: ["手动测试", "测试用例", "缺陷报告", "自动化"],
        },
      ],
    },
    experience: {
      kicker: "职业记录",
      title: "工作经历",
      summaryTitle: "经历概览",
      summary: "在实习岗位中参与生产系统、质量保证工作流和公共部门数据工具的开发与测试。",
      roleCount: "段实习经历",
      projectCount: "个个人项目",
      items: [
        {
          title: ".NET 开发实习生",
          company: "安大略省教育厅",
          period: "2024年9月 - 2024年12月",
          logo: "ontario",
          copy: "在开发实习期间，我参与了教育工作者和教育厅员工所使用的内部应用的开发与维护。我与开发人员及业务相关方合作，使用 .NET 技术和现代开发实践实现新功能、解决问题并改善应用的易用性。",
          tags: [".NET", "Web 应用", "跨团队协作"],
        },
        {
          title: "IT 质量保证助理实习生",
          company: "安大略省教育厅",
          period: "2024年1月 - 2024年8月",
          logo: "ontario",
          copy: "我负责保障安大略省教育应用的质量和可靠性，包括设计并执行测试用例、报告和复验缺陷，以及开发自动化脚本来提升测试效率，同时与开发和业务团队密切合作。",
          tags: ["质量保证", "自动化", "HP ALM"],
        },
        {
          title: "质量保证测试实习生",
          company: "Fresh City Farms",
          period: "2023年1月 - 2023年4月",
          logo: "fresh",
          copy: "在 Fresh City Farms，我为公司的电商平台和内部系统提供质量保证支持，执行功能与回归测试，记录包含详细复现步骤的缺陷，并与开发人员协作，确保用户体验稳定可靠。",
          tags: ["回归测试", "Jira", "电子商务"],
        },
      ],
    },
    contact: {
      titleBefore: "一起做点",
      titleAccent: "有用的东西",
      intro: "我愿意了解各种机会，希望参与实用产品的构建，认真贡献，并在创造影响的过程中持续成长。",
      messageTitle: "发送消息",
      message: "电子邮件是联系我的最快方式。请告诉我背景、需要解决的问题，以及你希望获得怎样的帮助。",
      copyEmail: "复制邮箱地址",
      copiedEmail: "邮箱地址已复制",
      networkTitle: "社交与职业平台",
      professionalProfile: "职业资料",
      resume: "简历",
      resumeDetail: "下载 PDF",
    },
    footer: {
      builtWith: "2026 // 使用 REACT 构建",
      status: "连接安全",
    },
  },
};
